services:
  web-frontend:
    build:
      context: ./frontend-web
      args:
        NEXT_PUBLIC_API_URL: http://backend:8080
    container_name: at-art_web
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    ports:
      - "3000:3000"
    networks:
      - at-art
    depends_on:
      - backend

networks:
  at-art:
    driver: bridge
