services:
  backend:
    build:
      context: ./backend
    container_name: art_backend
    restart: unless-stopped
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    networks:
      - art
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3

  web-frontend:
    build:
      context: ./frontend-web
      args:
        NEXT_PUBLIC_API_URL: http://backend:8080
    container_name: art_web
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL_WEB}
      - DOCKER=${DOCKER}
      - DATOCMS_READONLY_TOKEN=${DATOCMS_READONLY_TOKEN}
      - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
      - IMAGEKIT_FOLDERS=${IMAGEKIT_FOLDERS}
      - IMAGEKIT_LIMIT=${IMAGEKIT_LIMIT}
    ports:
      - "3000:3000"
    networks:
      - art
    depends_on:
      - backend

networks:
  art:
    driver: bridge
