export const defaultKeywords: string[] = [
    'Antonio Troiano',
    'Art',
    'Handcrafted Art',
    'Unique Paintings',
    'Contemporary Art',
    'Modern Artist',
    'Abstract Art',
    'Emotional Artworks',
    'Abstrakte Kunst',
    'Abstrakte Kunst Frankfurt',
    'Kunst',
    'Acryl Art',
    'Acrylic Art',
    'Abstrakt Kunst',
    'Kunst Frankfurt',
    'Kunst Abstrakt',
    'Abstrakte Bilder',
    'Abstrakt',
    'Acryl Malerei',
    'Malerei',
    'Malen mit Acryl',
    'Bilder malen',
    'Acrylfarben',
    'Malerei Kunst',
    'Moderne Kunst',
    'Gemälde',
];
