# General settings
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Limits for tests high
ratelimiter.requests=10000
ratelimiter.timeWindowSeconds=1

# Test specific CORS
app.cors.allowed-origins=http://localhost:3000

# Mail configs
spring.mail.username=dummy
spring.mail.password=dummy
mail.to=info@antonio-troiano.de
