# Log cleanup
spring.main.banner-mode=off

# General settings
logging.level.org.springframework.boot.autoconfigure=INFO

# Rate Limit Defaults
ratelimiter.requests=5
ratelimiter.timeWindowSeconds=60

# Mail service
spring.mail.host=smtp.ionos.de
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.to=${MAIL_USERNAME}

# Test specific CORS
app.cors.allowed-origins=http://localhost:3000,http://localhost:3001

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

# Healthcheck
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
