import type {Metadata} from "next";
import "./globals.css";
import {raleway, quicksand} from "./fonts";
import AdminWrapper from "@/components/AdminnWrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="de" className={`${raleway.variable} ${quicksand.variable}`}>
        <body>
        <AdminWrapper>{children}</AdminWrapper>
        </body>
        </html>
    );
}
